# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-03 13:09
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name=b'%d-%m-%Y')),
                ('time', models.DateTimeField(default=datetime.datetime(2018, 1, 3, 13, 9, 20, 773615, tzinfo=utc))),
                ('receiver', models.ManyToManyField(related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ManyToManyField(related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
