# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-24 09:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name=b'%d-%m-%Y')),
                ('time', models.DateTimeField(default=datetime.datetime(2017, 12, 24, 9, 26, 24, 415069, tzinfo=utc))),
            ],
        ),
    ]
