# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-03 16:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 3, 16, 48, 27, 584681, tzinfo=utc)),
        ),
    ]
