# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-17 15:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20170917_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='sender_one',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='sender_two',
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 17, 15, 16, 49, 611289, tzinfo=utc)),
        ),
    ]
