# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-03 17:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20180103_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 3, 17, 45, 54, 319759, tzinfo=utc)),
        ),
    ]
