# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-24 11:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20170917_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='typing',
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 24, 11, 11, 53, 971912, tzinfo=utc)),
        ),
    ]
