# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-24 11:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20170924_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender_two',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender_one',
            new_name='sender',
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 24, 11, 14, 39, 946705, tzinfo=utc)),
        ),
    ]
