# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-10 06:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20170924_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 10, 6, 29, 54, 170983, tzinfo=utc)),
        ),
    ]
