# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-21 06:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_auto_20171020_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 21, 6, 57, 55, 808245, tzinfo=utc)),
        ),
    ]
