# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-21 08:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_auto_20171021_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 21, 8, 18, 35, 683212, tzinfo=utc)),
        ),
    ]
