# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-21 17:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0011_auto_20171021_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 21, 17, 5, 34, 293130, tzinfo=utc)),
        ),
    ]
