# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-24 14:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0013_auto_20171021_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 24, 14, 46, 56, 216501, tzinfo=utc)),
        ),
    ]
