# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-24 16:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0017_auto_20171024_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 24, 16, 43, 23, 18204, tzinfo=utc)),
        ),
    ]
