# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-25 19:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0022_auto_20171025_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 25, 19, 3, 30, 772218, tzinfo=utc)),
        ),
    ]
