# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-25 19:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0023_auto_20171025_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 25, 19, 8, 10, 189396, tzinfo=utc)),
        ),
    ]
