# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-25 19:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0024_auto_20171025_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 25, 19, 11, 47, 490916, tzinfo=utc)),
        ),
    ]
