# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-27 14:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0027_auto_20171025_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 27, 14, 7, 29, 373633, tzinfo=utc)),
        ),
    ]
