# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-27 14:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0029_auto_20171027_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 27, 14, 13, 59, 720053, tzinfo=utc)),
        ),
    ]
