# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-07 14:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0033_auto_20171030_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 14, 7, 35, 266000, tzinfo=utc)),
        ),
    ]
