# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-14 13:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0036_auto_20171107_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 13, 11, 43, 951000, tzinfo=utc)),
        ),
    ]
