# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-15 14:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0037_auto_20171114_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 15, 14, 33, 1, 175000, tzinfo=utc)),
        ),
    ]
