# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-17 10:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0038_auto_20171213_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 17, 10, 6, 48, 387474, tzinfo=utc)),
        ),
    ]
