# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-28 16:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0038_auto_20171115_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 28, 16, 36, 8, 514000, tzinfo=utc)),
        ),
    ]
