# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-03 09:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0039_auto_20171128_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 3, 9, 42, 7, 457000, tzinfo=utc)),
        ),
    ]
