# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-03 10:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0041_auto_20171203_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 3, 10, 17, 9, 395000, tzinfo=utc)),
        ),
    ]
