# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-05 13:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0046_auto_20171203_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 5, 13, 1, 13, 361000, tzinfo=utc)),
        ),
    ]
