# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-05 14:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0048_auto_20171205_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 5, 14, 19, 29, 558000, tzinfo=utc)),
        ),
    ]
