# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-08 14:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0049_auto_20171205_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 8, 14, 3, 23, 299000, tzinfo=utc)),
        ),
    ]
