# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-19 14:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0096_auto_20171219_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 19, 14, 38, 39, 413000, tzinfo=utc)),
        ),
    ]
