# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-22 19:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0097_auto_20171219_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 22, 19, 19, 12, 772000, tzinfo=utc)),
        ),
    ]
