# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-27 13:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0100_auto_20171227_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 27, 13, 24, 45, 276000, tzinfo=utc)),
        ),
    ]
