# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-02 10:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0101_auto_20171227_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 2, 10, 5, 0, 562000, tzinfo=utc)),
        ),
    ]
