# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-24 16:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkGroups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkgroup',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
