# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-25 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vkGroups', '0002_auto_20171024_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vkgroup',
            name='users',
        ),
    ]
