# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-13 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkGroups', '0003_remove_vkgroup_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkgroup',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='vkgroup',
            name='status',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
