# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-03 13:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vkGroups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('workplace', models.CharField(max_length=100)),
                ('user_foto', models.CharField(max_length=150)),
                ('birthDate', models.DateField()),
                ('hometown', models.CharField(max_length=100)),
                ('urlid', models.CharField(default=b'', max_length=100)),
                ('timeSetPassword', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('vk_id', models.CharField(max_length=100)),
                ('listOfFriends', models.ManyToManyField(related_name='_user_listOfFriends_+', to=settings.AUTH_USER_MODEL)),
                ('listOfIncoming', models.ManyToManyField(related_name='_user_listOfIncoming_+', to=settings.AUTH_USER_MODEL)),
                ('listOfOutcoming', models.ManyToManyField(related_name='_user_listOfOutcoming_+', to=settings.AUTH_USER_MODEL)),
                ('vk_groups', models.ManyToManyField(db_index=True, related_name='vk_groups', to='vkGroups.vkGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
