# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-03 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthtown',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='citations',
            field=models.ManyToManyField(related_name='citations', to='quote.Quote'),
        ),
        migrations.AddField(
            model_name='user',
            name='maidenName',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='maritalstatus',
            field=models.CharField(default=b'1', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='politicalBeliefs',
            field=models.CharField(default=b'0', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='religiousBeliefs',
            field=models.CharField(default=b'0', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default=b'1', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='showBirthDate',
            field=models.CharField(default=b'0', max_length=10),
        ),
    ]
