# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0002_remove_user_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateField(),
        ),
    ]
