# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0003_auto_20170815_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timeSetPassword',
            field=models.DateField(auto_now=True),
        ),
    ]
