# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-09 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0004_user_timesetpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='urlid',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
