# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0005_auto_20170812_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateField(auto_now=True),
        ),
    ]
