# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0006_auto_20170812_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_foto',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateField(),
        ),
    ]
