# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0007_auto_20170814_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='workplace',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_foto',
            field=models.CharField(max_length=150),
        ),
    ]
