# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-13 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0007_auto_20170813_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
