# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-10 06:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0007_auto_20170917_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listOfFriends',
            field=models.ManyToManyField(related_name='_user_listOfFriends_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='listOfIncoming',
            field=models.ManyToManyField(related_name='_user_listOfIncoming_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='listOfOutcoming',
            field=models.ManyToManyField(related_name='_user_listOfOutcoming_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='vk_id',
            field=models.CharField(default=1968, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='timeSetPassword',
            field=models.DateField(auto_now=True),
        ),
    ]
