# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-25 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkGroups', '0003_remove_vkgroup_users'),
        ('society', '0008_auto_20171010_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vk_groups',
            field=models.ManyToManyField(related_name='vk_groups', to='vkGroups.vkGroup'),
        ),
    ]
