# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-07 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0009_user_vk_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthtown',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='maidenName',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='maritalstatus',
            field=models.CharField(default=b'1', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default=b'1', max_length=10),
        ),
    ]
