# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-13 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vkGroups', '0004_auto_20171213_1430'),
        ('society', '0009_user_vk_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vk_groups',
        ),
        migrations.AddField(
            model_name='user',
            name='vk_groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vk_groups', to='vkGroups.vkGroup'),
        ),
    ]
