# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-14 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0010_auto_20171107_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='citations',
            field=models.ManyToManyField(related_name='_user_citations_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='politicalBeliefs',
            field=models.CharField(default=b'0', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='religiousBeliefs',
            field=models.CharField(default=b'0', max_length=10),
        ),
    ]
