# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-17 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkGroups', '0004_auto_20171213_1430'),
        ('society', '0010_auto_20171213_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vk_groups',
        ),
        migrations.AddField(
            model_name='user',
            name='vk_groups',
            field=models.ManyToManyField(db_index=True, related_name='vk_groups', to='vkGroups.vkGroup'),
        ),
    ]
