# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-03 10:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0011_auto_20171114_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='listOfIncoming',
        ),
        migrations.AddField(
            model_name='user',
            name='listOfIncoming',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='user',
            name='listOfOutcoming',
        ),
        migrations.AddField(
            model_name='user',
            name='listOfOutcoming',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
