# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-03 10:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0012_auto_20171203_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='listOfIncoming',
        ),
        migrations.AddField(
            model_name='user',
            name='listOfIncoming',
            field=models.ManyToManyField(related_name='_user_listOfIncoming_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='user',
            name='listOfOutcoming',
        ),
        migrations.AddField(
            model_name='user',
            name='listOfOutcoming',
            field=models.ManyToManyField(related_name='_user_listOfOutcoming_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
