# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-08 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0013_auto_20171203_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='citations',
        ),
    ]
