# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-12 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0014_remove_user_citations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='showBirthDate',
            field=models.CharField(default=b'0', max_length=10),
        ),
    ]
