# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-15 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0015_user_showbirthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='citations',
            field=models.CharField(default=b'', max_length=1000),
        ),
    ]
