# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-15 15:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0016_user_citations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='citations',
        ),
        migrations.AddField(
            model_name='user',
            name='citations',
            field=models.ManyToManyField(related_name='_user_citations_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
