# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-17 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
        ('society', '0018_remove_user_citations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='citations',
            field=models.ManyToManyField(related_name='citations', to='quote.Quote'),
        ),
    ]
