# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-17 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0019_user_citations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='citations',
            field=models.ManyToManyField(related_name='_user_citations_+', to='quote.Quote'),
        ),
    ]
