# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-27 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0021_auto_20171219_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='workplace',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
